### ISSUE TITLE
"Find more..." button in Project drop down does not work

### ISSUE THREAD

**Issue by bhuber2010** [phase2/openair-reborn#9] opened 2014-07-24 18:15 UTC
![2014-07-24 10_20_17-openair _ timesheets _ adaptive planning](https://cloud.githubusercontent.com/assets/4156395/3692627/6af64f84-135e-11e4-90be-546bceb38a86.png)

**Comment by crittermike** [comment] 2014-07-24 18:21
I'm having trouble reproducing this one too. I just manually added over 300
to test with and it showed all 300. Does the OpenAir select show all of
them, or does "Find more" exist there too? How many do show up?

**Comment by bhuber2010** [comment] 2014-07-24 18:48
This is the only way we can search for all the items in Projects in this UI. Once the item is chosen though, it will then be contained in the "short list" dropdown going forward in the Edit view.
![2014-07-24 11_43_32-_find more _ button in project drop down does not work issue 9 mikecritte](https://cloud.githubusercontent.com/assets/4156395/3693017/7f2eb87a-1362-11e4-853e-af9470ca1d92.png)

**Comment by crittermike** [comment] 2014-07-24 18:54
Ah, I gotcha. How many projects do you guys have? That must be the
issue--we have few enough projects that they are all in the list and we
don't have to search.

I think the workaround you're using now might be the best we can do for
now, since making the extension trigger OA's project search would be
non-trivial as far as I can tell.

**Comment by bhuber2010** [comment] 2014-08-01 17:20
The first drop down for us is "Client : Project" so it lists each client:project combo available and thus the list gets very long. Our second field/drop down is Task which is more limited and working fine.

**Comment by crittermike** [comment] 2014-08-08 04:02
I'm going to close this since a proper fix would be extremely difficult from the looks of things, and there's an easy enough workaround, plus it doesn't seem like a very often occurrence for most people.

**Closed as completed by crittermike** 2014-08-08 04:02 UTC
Labels: bug

**Comment by bhuber2010** [comment] 2014-09-03 15:51
I almost swear this started working for a little and just noticed it doesn't again. I haven't been using it much lately as just copying previous timecards. No big deal, just thought I'd throw it out there that unless I dreamt it, I believe it did work for a build within the past couple weeks. Thanks!
